version: '3.1'

services:

  webshop:
    image: nenadkocev/web-shop:0.0.1-SNAPSHOT
    environment:
      - SERVER_PORT=8080
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - TOKENIZER_URL=http://tokenizer:8080
    ports:
      - 8082:8080

  tokenizer:
    image: nenadkocev/tokenizer:0.0.1-SNAPSHOT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tokenizer_db
    ports:
      - 8081:8080

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: tokenizer
      POSTGRES_USER: tokenizer
      POSTGRES_DB: tokenizer_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

volumes:
  postgres: