pipeline {
    agent any
    tools {
        maven 'Maven 3.6.3'
        jdk 'jdk17'
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }

        stage ('Login') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }

        stage ('Build') {
            steps {
                script {
                    sh "mvn --projects card-tokenizer --also-make clean install"
                }
            }
        }
    }
}