pipeline {
    agent any
    tools {
        maven 'Maven 3.6.3'
        jdk 'jdk17'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }

        stage ('Build') {
            steps {
                script {
                sh "mvn --projects card-tokenizer --also-make clean install"
                }
            }
        }
    }
}